### ISSUE TITLE
Descriptiosn Needed

### ISSUE THREAD

**Issue by LokeshYarramallu** [LokeshYarramallu/AM_ACM-AI_ML_Models#14]
need a clear explanation of dimentionality reduction and its use cases along ith importance in ML model making
should make a readme.md file in SVD and PCM folders and explain about dimentionality reduction adn process of SVD and PCM in respective folders along with images and steps and further information

**Comment by Kaushik-2005** [comment]
Wrote readme.md for the explanation of SVD

**Comment by Avishek8136** [comment]
Provided Description about PCA in Readme.md
