### ISSUE TITLE
The first contribution

### ISSUE THREAD

**Issue by LokeshYarramallu** [LokeshYarramallu/AM_ACM-AI_ML_Models#2]
make a first contribution to the repository and also get included with hacktober fest

**Comment by abhinavn2206146** [comment]
Hey @LokeshYarramallu , Do assign this to me under hacktoberfest 2023

I kindly request that this issue be assigned to me.

Thank you for your assistance!

Best regards,
@abhinavn2206146

**Comment by LokeshYarramallu** [comment]
sure, thank you for making in into this repository ill assaign this to you
