### ISSUE TITLE
Linear Regression

### ISSUE THREAD

**Issue by LokeshYarramallu** [LokeshYarramallu/AM_ACM-AI_ML_Models#3]
Make a contribution under Linear Regression

**Comment by sukhmani1303** [comment]
kindly assign me this issue

**Comment by raji2004** [comment]
please assign me this issue

**Comment by shubhjaiswal02** [comment]
I've sent a pull request. Please review it and let me know if you require any changes.
Thanks

**Comment by LokeshYarramallu** [comment]
thank you for contributing

**Comment by LokeshYarramallu** [comment]
can you please cahnge the folder name with the dataset title you are training
