### ISSUE TITLE
Logistic Regression

### ISSUE THREAD

**Issue by LokeshYarramallu** [LokeshYarramallu/AM_ACM-AI_ML_Models#5]
Make a contribution under Logistic Regression

**Comment by avi-dey** [comment]
I am picking this up. I have to perform Logistic Regression on any dateset as per my wish, right?

**Comment by LokeshYarramallu** [comment]
yes data preprocessing is mandatory and detailed documentation

**Comment by Avishek8136** [comment]
I am picking it up. Almost completed with news classification .

**Comment by Avishek8136** [comment]
ok

**Comment by Avishek8136** [comment]
[Completed Fake News Classification using Logistic Regression and NLP](https://github.com/LokeshYarramallu/AM_ACM-AI_ML_Models/pull/32)
